# Generated by Django 4.0.1 on 2022-02-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_book_author_alter_book_language_and_more'),
        ('users', '0007_remove_profile_id_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='books.Book'),
        ),
    ]
