# Generated by Django 4.0.1 on 2022-02-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_alter_comment_content'),
        ('users', '0008_profile_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(blank=True, to='books.Book'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='books.Book'),
        ),
    ]
