# Generated by Django 4.0.1 on 2022-01-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_posted_by_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='default_book.jpg', upload_to='books_pics'),
        ),
    ]
