# Generated by Django 4.0.1 on 2022-01-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_genre_book_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='one off'),
            preserve_default=False,
        ),
    ]
