# Generated by Django 4.0.1 on 2022-01-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_author_alter_book_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(max_length=100),
        ),
    ]
