# Generated by Django 4.0.1 on 2022-01-23 13:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0008_alter_book_genre_alter_book_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AddField(
            model_name='book',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
