# Generated by Django 4.0.1 on 2022-01-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('ART', 'Art'), ('BIOGRAPHY', 'Biography'), ('COMEDY', 'Comedy'), ('CLASSIC', 'Classic'), ('HEALTH', 'Health'), ('HISTORY', 'History'), ('THRILLER', 'Thriller'), ('OTHER', 'Other')], default='ART', max_length=9),
        ),
    ]
