# Generated by Django 4.0.1 on 2022-03-01 21:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_alter_comment_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1)])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1)])),
                ('image', models.URLField()),
                ('birth_date', models.DateField()),
                ('biography', models.TextField()),
            ],
        ),
    ]
